openapi: 3.0.2
info:
  title: KafkaSteelIO
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /get/all/{offset}/{topic}/{group_id}:
    get:
      summary: Get all messages from a topic in Kafka 
      parameters:
        - name: offset
          in: path
          description: The offset to start consuming messages from - earliest
          required: true
          schema:
            type: string
        - name: topic
          in: path
          description: The Kafka topic to consume messages from
          required: true
          schema:
            type: string
        - name: group_id
          in: path
          description: The Kafka consumer group ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Failed to retrieve messages
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /get/{offset}/{topic}/{group_id}:
    get:
      summary: Get latest messages - set offset as latest
      parameters:
        - name: offset
          in: path
          description: The offset to start consuming messages from - latest
          required: true
          schema:
            type: string
        - name: topic
          in: path
          description: The Kafka topic to consume messages from
          required: true
          schema:
            type: string
        - name: group_id
          in: path
          description: The Kafka consumer group ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Failed to retrieve messages
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /get/time-range/{offset}/{topic}/{group_id}/{start_time}/{end_time}:
    get:
      summary: Get messages within a time range from a topic
      parameters:
        - name: offset
          in: path
          description: The offset to start consuming messages from (either 'earliest' or 'latest')
          required: true
          schema:
            type: string
        - name: topic
          in: path
          description: The Kafka topic to consume messages from
          required: true
          schema:
            type: string
        - name: group_id
          in: path
          description: The Kafka consumer group ID
          required: true
          schema:
            type: string
        - name: start_time
          in: path
          description: The start time of the time range in ISO 8601 format
          required: true
          schema:
            type: string
            format: date-time
        - name: end_time
          in: path
          description: The end time of the time range in ISO 8601 format
          required: true
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Failed to retrieve messages
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /get/key-value/{offset}/{topic}/{group_id}/{key}/{value}:
    get:
      summary: Get messages by key-value pair
      parameters:
        - name: offset
          in: path
          description: The offset to start consuming messages from (either 'earliest' or 'latest')
          required: true
          schema:
            type: string
        - name: topic
          in: path
          description: The Kafka topic to consume messages from
          required: true
          schema:
            type: string
        - name: group_id
          in: path
          description: The Kafka consumer group ID
          required: true
          schema:
            type: string
        - name: key
          in: path
          description: The key to search for in the messages
          required: true
          schema:
            type: string
        - name: value
          in: path
          description: The value to match with the specified key
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Failed to retrieve messages
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /get/name-time-range/{offset}/{topic}/{group_id}/{start_time}/{end_time}/{name}:
    get:
      summary: Get messages by name and time range
      parameters:
        - name: offset
          in: path
          description: The offset to start consuming messages from (either 'earliest' or 'latest')
          required: true
          schema:
            type: string
        - name: topic
          in: path
          description: The Kafka topic to consume messages from
          required: true
          schema:
            type: string
        - name: group_id
          in: path
          description: The Kafka consumer group ID
          required: true
          schema:
            type: string
        - name: start_time
          in: path
          description: The start time in the format "YYYY-MM-DDTHH:MM:SS.ssssss"
          required: true
          schema:
            type: string
        - name: end_time
          in: path
          description: The end time in the format "YYYY-MM-DDTHH:MM:SS.ssssss"
          required: true
          schema:
            type: string
        - name: name
          in: path
          description: The name of the sensor (optional)
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Failed to retrieve messages
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /get_partitions/{partition_nums}/{offset}/{topic}/{group_id}:
    get:
      summary: Get messages from one or multiple partitions
      parameters:
        - name: partition_nums
          in: path
          description: Comma-separated list of partition numbers to consume messages from
          required: true
          schema:
            type: string
        - name: offset
          in: path
          description: The offset to start consuming messages from (either 'earliest' or 'latest')
          required: true
          schema:
            type: string
        - name: topic
          in: path
          description: The Kafka topic to consume messages from
          required: true
          schema:
            type: string
        - name: group_id
          in: path
          description: The Kafka consumer group ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Failed to retrieve messages
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /get_partition_id/{topic}/{partition_key}/{group_id}:
    get:
      summary: Get partition ID by partition key
      parameters:
        - name: topic
          in: path
          description: The Kafka topic to get the partition ID from
          required: true
          schema:
            type: string
        - name: partition_key
          in: path
          description: The partition key
          required: true
          schema:
            type: string
        - name: group_id
          in: path
          description: The Kafka consumer group ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: integer
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /get/payload/{offset}/{topic}/{group_id}:
    get:
      summary: Get payload from Kafka topic (RDBMS data)
      parameters:
        - name: offset
          in: path
          description: The offset to start consuming messages from ('earliest' or 'latest')
          required: true
          schema:
            type: string
        - name: topic
          in: path
          description: The Kafka topic to consume messages from
          required: true
          schema:
            type: string
        - name: group_id
          in: path
          description: The Kafka consumer group ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /get/schema/{topic}/{group_id}:
    get:
      summary: Get the latest message schema from Kafka topic
      parameters:
        - name: topic
          in: path
          description: The Kafka topic to retrieve the latest message schema from
          required: true
          schema:
            type: string
        - name: group_id
          in: path
          description: The Kafka consumer group ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    field:
                      type: string
        '404':
          description: Schema not found
        '500':
          description: Internal server error
  /get/{offset}/{topic}/{group_id}/{n}:
    get:
      summary: Get n messages from a Kafka topic
      parameters:
        - name: offset
          in: path
          description: The offset to start consuming messages from ("earliest" or "latest")
          required: true
          schema:
            type: string
            enum: ['earliest', 'latest']
        - name: topic
          in: path
          description: The Kafka topic to consume messages from
          required: true
          schema:
            type: string
        - name: group_id
          in: path
          description: The Kafka consumer group ID
          required: true
          schema:
            type: string
        - name: n
          in: path
          description: The number of messages to retrieve
          required: true
          schema:
            type: integer
            minimum: 1
        - name: partition_key
          in: query
          description: The partition key to filter messages from a specific partition
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        '400':
          description: Bad request
        '404':
          description: Partition ID not found
        '500':
          description: Internal server error