# Use the official Python base image with version tag
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements.txt file to the container
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire backend code to the container
COPY . .

# Set the command to start the backend server
CMD [ "python", "app.py" ]
